### ISSUE TITLE
Force sudo prompt

### ISSUE THREAD

**Issue by Jonchun** [Jonchun/macify-linux#17]
Currently, the setup script will prompt
```
This script will require sudo permissions for certain actions. You may be prompted for your credentials.
```
However, it won't ask this if the sudo credentials have already been cached in the terminal session. (e.g. if the user has recently run `sudo apt-get install git`). 

It should definitely be made explicit that this script will be using sudo permissions since the python process itself is NOT executed as superuser. In fact, I'm wondering if this is a big security oversight? Can an expert help me out here?

The fix should be simple enough:
```
man sudo
...
...
     -k, --reset-timestamp
                 When used without a command, invalidates the user's cached credentials.  In other words, the next
                 time sudo is run a password will be required.  This option does not require a password and was
                 added to allow a user to revoke sudo permissions from a .logout file.

                 When used in conjunction with a command or an option that may require a password, this option will
                 cause sudo to ignore the user's cached credentials.  As a result, sudo will prompt for a password
                 (if one is required by the security policy) and will not update the user's cached credentials.

                 Not all security policies support credential caching.

**Comment by Konfekt** [comment]
The following check achieves this:

```sh
if [ $(id -u) -ne 0 ]; then
  echo "Please run as root by sudo!"
  exit
fi
```

**Comment by Jonchun** [comment]
That is actually the opposite of what I want. I don't want the entire script to be running as root. I want to explicitly call `sudo` from `subprocess` only for the actions that require it. The rest of the script should be run as your primary user.

**Comment by Konfekt** [comment]
This 

> explicitly call sudo from subprocess only for the actions that require it

makes it clearer what this issue is about. In a shell script, indeed only files created using `sudo` will have root ownership despite cached credentials. Thus I must conclude that I do not even understand why the problem occurs under Python. Hopefully it will be clear to others that can help you.

**Comment by Jonchun** [comment]
So just for clarity: I know exactly how to resolve this issue. I was just documenting it so I can revisit it at a later time.

However, I do want to clarify here for anyone browsing this in the future. If you have the following **test.py**
```
import subprocess
subprocess.run("whoami", shell=True)
subprocess.run("id -u", shell=True)
subprocess.run("sudo whoami", shell=True)
subprocess.run("sudo id -u", shell=True)
```
here is what happens if you're executing the program in a terminal session:
```
jchun  ~  python3 test.py 
jchun
1000
[sudo] password for jchun: 
root
0
jchun  ~  python3 test.py 
jchun
1000
root
0
```
Note how the `[sudo] password` prompts only ONCE. the second time I run the program, even though I'm running `test.py` WITHOUT a `sudo`, I'm clearly able to access `sudo` permissions without the user explicitly confirming the password because it's already cached. I need to clear the cache first with `sudo -k` in order to achieve this.

This was a problem because this could happen
```
 jchun  ~  sudo -k
 jchun  ~  sudo apt-get install git
[sudo] password for jchun: 
...
...
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
 jchun  ~  python3 test.py 
jchun
1000
root
0
````
You can see that my `test.py` runs as root without ever prompting the user since the `sudo` credentials were already cached from the `apt-get` command previously.
