### ISSUE TITLE
Investigate crashes on laptop

### ISSUE THREAD

**Issue by Jonchun** [Jonchun/macify-linux#37]
Haven't tested this too much, but on baremetal laptop, KDE Neon seems to be freezing up constantly. A fresh install of KDE Neon and running this script seems to trigger it. Perhaps one of the master branches I'm installing from is now unstable?

Trying out just plain Ubuntu to see if it's a problem with my hardware or with this script or with KDE Neon

**Comment by Jonchun** [comment]
This seems to happen in a VM as well now. Currently unsure of what it is and haven't had time to investigate.

**Comment by Jonchun** [comment]
Something definitely broke. If I go into System Settings I see this:
![image](https://user-images.githubusercontent.com/5800539/80135086-b30b1980-856d-11ea-97b5-c7d3b68c51d9.png)

Checking to see if I can just `apt-get upgrade -y` to fix it.

**Comment by Jonchun** [comment]
Ran `apt-get upgrade -y` before running my script to see if that did the trick. It seems to crash pretty quickly still, so that didn't do the trick.

At this point I'll probably need to disable components one by one until I figure out which one is causing the crash. I suspect it might be the kde-hello theming which is causing it, but unsure. It's weird because my desktop environment is operating perfectly fine with no crashes.

**Comment by Jonchun** [comment]
Switched script to install latte-dock from apt rather than source by default and seems to have fixed the issue. Will do further testing before closing this out. Haven't tested against laptop yet.

**Comment by jonchun** [comment]
Laptop has been working fine for days. Closing this out. Must have been instability with the latest master branch of latte-dock.
